services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: historian_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} && psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c \"SELECT 1 FROM pg_roles WHERE rolname = 'grafana_reader';\"" ]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 5s

  simulator:
    build: ./simulator
    container_name: historian_simulator
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@timescaledb:5432/${POSTGRES_DB}
      AUTO_SEED_DAYS: ${AUTO_SEED_DAYS}
    depends_on:
      timescaledb:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    container_name: historian_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=FT1234
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafanadata:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      timescaledb:
        condition: service_healthy

volumes:
  pgdata:
  grafanadata:
